config/routes.rb
Wine::Application.routes.draw do
  resources :owners

  resources :formats

  resources :offerings

  resources :cellars

  resources :bottles

  resources :compositions

  resources :users

  resources :regions

  resources :countries

  resources :colors

  resources :producers

  resources :grapes

  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => 'pages#home'

end

app/models/bottle.rb
class Bottle < ActiveRecord::Base

  belongs_to :cellar
  belongs_to :offering
  belongs_to :format

end

app/models/cellar.rb
class Cellar < ActiveRecord::Base

  has_many :bottles
  has_many :owners
  has_many :users, :through => :owners

end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :grapes
  has_many :offerings
end

app/models/composition.rb
class Composition < ActiveRecord::Base

  belongs_to :grape
  belongs_to :offering
  
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :regions
end

app/models/format.rb
class Format < ActiveRecord::Base
  has_many :bottles
end

app/models/grape.rb
class Grape < ActiveRecord::Base

  belongs_to :color
  has_many :compositions
  
end

app/models/offering.rb
class Offering < ActiveRecord::Base
  belongs_to :producer
  belongs_to :color
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :user
  belongs_to :cellar
end

app/models/producer.rb
class Producer < ActiveRecord::Base

  has_many :offerings
  belongs_to :region

end

app/models/region.rb
class Region < ActiveRecord::Base
  belongs_to :country
  has_many :producers
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password
  attr_accessible :name, :email, :description, :phone, :password, :password_confirmation

  has_many :owners
  has_many :cellars, :through => :owners



  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true, :length => { :maximum => 50 }
  validates :email, :presence => true, :format => { :with => email_regex }, :uniqueness => { :case_sensitive => false }

  # automatically creates the virtual attribute 'password_confirmation'
  validates :password, :presence => true, :confirmation => true, :length => { :within => 6..40 }

  before_save :encrypt_password

  default_scope :order => 'users.name ASC'

  # return true if the user's password matches the submitted password
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/compositions_controller.rb
class CompositionsController < ApplicationController
  # GET /compositions
  # GET /compositions.xml
  def index
    @compositions = Composition.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @compositions }
    end
  end

  # GET /compositions/1
  # GET /compositions/1.xml
  def show
    @composition = Composition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @composition }
    end
  end

  # GET /compositions/new
  # GET /compositions/new.xml
  def new
    @composition = Composition.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @composition }
    end
  end

  # GET /compositions/1/edit
  def edit
    @composition = Composition.find(params[:id])
  end

  # POST /compositions
  # POST /compositions.xml
  def create
    @composition = Composition.new(params[:composition])

    respond_to do |format|
      if @composition.save
        format.html { redirect_to(@composition, :notice => 'Composition was successfully created.') }
        format.xml  { render :xml => @composition, :status => :created, :location => @composition }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @composition.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /compositions/1
  # PUT /compositions/1.xml
  def update
    @composition = Composition.find(params[:id])

    respond_to do |format|
      if @composition.update_attributes(params[:composition])
        format.html { redirect_to(@composition, :notice => 'Composition was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @composition.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /compositions/1
  # DELETE /compositions/1.xml
  def destroy
    @composition = Composition.find(params[:id])
    @composition.destroy

    respond_to do |format|
      format.html { redirect_to(compositions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/bottles_helper.rb
module BottlesHelper
end

app/helpers/cellars_helper.rb
module CellarsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/compositions_helper.rb
module CompositionsHelper
end

app/helpers/formats_helper.rb
module FormatsHelper
end

app/helpers/grapes_helper.rb
module GrapesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def authenticate
    deny_access unless signed_in?
  end

  def deny_access
    store_location
    redirect_to signin_path, :notice => 'Please sign in to access this page.'
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

    def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/compositions/_form.html.erb
<%= form_for(@composition) do |f| %>
  <% if @composition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@composition.errors.count, "error") %> prohibited this composition from being saved:</h2>

      <ul>
      <% @composition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :grape_id %><br />
    <%= f.collection_select(:grape_id, Grape.all, :id, :common_name) %>
  </div>
  <div class="field">
    <%= f.label :offering_id %><br />
    <%= f.collection_select(:offering_id, Offering.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/compositions/edit.html.erb
<h1>Editing composition</h1>

<%= render 'form' %>

<%= link_to 'Show', @composition %> |
<%= link_to 'Back', compositions_path %>

app/views/compositions/index.html.erb
<h1>Listing compositions</h1>

<table>
  <tr>
    <th>Grape</th>
    <th>Offering</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @compositions.each do |composition| %>
  <tr>
    <td><%= composition.grape.common_name %></td>
    <td><%= composition.offering.name %></td>
    <td><%= link_to 'Show', composition %></td>
    <td><%= link_to 'Edit', edit_composition_path(composition) %></td>
    <td><%= link_to 'Destroy', composition, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Composition', new_composition_path %>

app/views/compositions/new.html.erb
<h1>New composition</h1>

<%= render 'form' %>

<%= link_to 'Back', compositions_path %>

app/views/compositions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Grape:</b>
  <%= @composition.grape_id %>
</p>

<p>
  <b>Offering:</b>
  <%= @composition.offering_id %>
</p>


<%= link_to 'Edit', edit_composition_path(@composition) %> |
<%= link_to 'Back', compositions_path %>