config/routes.rb
Wine::Application.routes.draw do
  resources :owners

  resources :formats

  resources :offerings

  resources :cellars

  resources :bottles

  resources :compositions

  resources :users

  resources :regions

  resources :countries

  resources :colors

  resources :producers

  resources :grapes

  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => 'pages#home'

end

app/models/bottle.rb
class Bottle < ActiveRecord::Base

  belongs_to :cellar
  belongs_to :offering
  belongs_to :format

end

app/models/cellar.rb
class Cellar < ActiveRecord::Base

  has_many :bottles
  has_many :owners
  has_many :users, :through => :owners

end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :grapes
  has_many :offerings
end

app/models/composition.rb
class Composition < ActiveRecord::Base

  belongs_to :grape
  belongs_to :offering
  
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :regions
end

app/models/format.rb
class Format < ActiveRecord::Base
  has_many :bottles
end

app/models/grape.rb
class Grape < ActiveRecord::Base

  belongs_to :color
  has_many :compositions
  
end

app/models/offering.rb
class Offering < ActiveRecord::Base
  belongs_to :producer
  belongs_to :color
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :user
  belongs_to :cellar
end

app/models/producer.rb
class Producer < ActiveRecord::Base

  has_many :offerings
  belongs_to :region

end

app/models/region.rb
class Region < ActiveRecord::Base
  belongs_to :country
  has_many :producers
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password
  attr_accessible :name, :email, :description, :phone, :password, :password_confirmation

  has_many :owners
  has_many :cellars, :through => :owners



  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true, :length => { :maximum => 50 }
  validates :email, :presence => true, :format => { :with => email_regex }, :uniqueness => { :case_sensitive => false }

  # automatically creates the virtual attribute 'password_confirmation'
  validates :password, :presence => true, :confirmation => true, :length => { :within => 6..40 }

  before_save :encrypt_password

  default_scope :order => 'users.name ASC'

  # return true if the user's password matches the submitted password
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
  # GET /bottles
  # GET /bottles.xml
  def index
    @bottles = Bottle.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bottles }
    end
  end

  # GET /bottles/1
  # GET /bottles/1.xml
  def show
    @bottle = Bottle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bottle }
    end
  end

  # GET /bottles/new
  # GET /bottles/new.xml
  def new
    @bottle = Bottle.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bottle }
    end
  end

  # GET /bottles/1/edit
  def edit
    @bottle = Bottle.find(params[:id])
  end

  # POST /bottles
  # POST /bottles.xml
  def create
    @bottle = Bottle.new(params[:bottle])

    respond_to do |format|
      if @bottle.save
        format.html { redirect_to(@bottle, :notice => 'Bottle was successfully created.') }
        format.xml  { render :xml => @bottle, :status => :created, :location => @bottle }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bottle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bottles/1
  # PUT /bottles/1.xml
  def update
    @bottle = Bottle.find(params[:id])

    respond_to do |format|
      if @bottle.update_attributes(params[:bottle])
        format.html { redirect_to(@bottle, :notice => 'Bottle was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bottle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bottles/1
  # DELETE /bottles/1.xml
  def destroy
    @bottle = Bottle.find(params[:id])
    @bottle.destroy

    respond_to do |format|
      format.html { redirect_to(bottles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/bottles_helper.rb
module BottlesHelper
end

app/helpers/cellars_helper.rb
module CellarsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/formats_helper.rb
module FormatsHelper
end

app/helpers/grapes_helper.rb
module GrapesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def authenticate
    deny_access unless signed_in?
  end

  def deny_access
    store_location
    redirect_to signin_path, :notice => 'Please sign in to access this page.'
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

    def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bottles/_bottle.html.erb
  <tr>
    <td><%= bottle.cellar.name %></td>
    <td><%= bottle.offering.name %></td>
    <td><%= bottle.year %></td>
    <td><%= bottle.number %></td>
    <td><%= bottle.comment %></td>
    <td><%= bottle.format.name %></td>
    <td><%= link_to 'Show', bottle %></td>
    <td><%= link_to 'Edit', edit_bottle_path(bottle) %></td>
    <td><%= link_to 'Destroy', bottle, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>

app/views/bottles/_bottle_set.html.erb
<table>
  <thead>
    <th>Cellar</th>
    <th>Wine</th>
    <th>Year</th>
    <th>Number</th>
    <th>Comment</th>
    <th>Format</th>
    <th></th>
    <th></th>
    <th></th>
  </thead>
  <tbody>
    <%= render @bottles %>
  </tbody>
</table>

app/views/bottles/_form.html.erb
<%= form_for(@bottle) do |f| %>
  <% if @bottle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bottle.errors.count, "error") %> prohibited this bottle from being saved:</h2>

      <ul>
      <% @bottle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cellar_id %><br />
    <%= f.collection_select(:cellar_id, Cellar.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :offering_id %><br />
    <%= f.collection_select(:offering_id, Offering.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :format_id %><br />
    <%= f.collection_select(:format_id, Format.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bottles/edit.html.erb
<h1>Editing bottle</h1>

<%= render 'form' %>

<%= link_to 'Show', @bottle %> |
<%= link_to 'Back', bottles_path %>

app/views/bottles/index.html.erb
<h1>Listing bottles</h1>

<%= render 'bottles/bottle_set' %>

<br />

<%= link_to 'New Bottle', new_bottle_path %>

app/views/bottles/new.html.erb
<h1>New bottle</h1>

<%= render 'form' %>

<%= link_to 'Back', bottles_path %>

app/views/bottles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cellar:</b>
  <%= @bottle.cellar %>
</p>

<p>
  <b>Offering:</b>
  <%= @bottle.offering_id %>
</p>

<p>
  <b>Year:</b>
  <%= @bottle.year %>
</p>

<p>
  <b>Number:</b>
  <%= @bottle.number %>
</p>

<p>
  <b>Comment:</b>
  <%= @bottle.comment %>
</p>

<p>
  <b>Format:</b>
  <%= @bottle.format_id %>
</p>


<%= link_to 'Edit', edit_bottle_path(@bottle) %> |
<%= link_to 'Back', bottles_path %>