config/routes.rb
Wine::Application.routes.draw do
  resources :owners

  resources :formats

  resources :offerings

  resources :cellars

  resources :bottles

  resources :compositions

  resources :users

  resources :regions

  resources :countries

  resources :colors

  resources :producers

  resources :grapes

  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => 'pages#home'

end

app/models/bottle.rb
class Bottle < ActiveRecord::Base

  belongs_to :cellar
  belongs_to :offering
  belongs_to :format

end

app/models/cellar.rb
class Cellar < ActiveRecord::Base

  has_many :bottles
  has_many :owners
  has_many :users, :through => :owners

end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :grapes
  has_many :offerings
end

app/models/composition.rb
class Composition < ActiveRecord::Base

  belongs_to :grape
  belongs_to :offering
  
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :regions
end

app/models/format.rb
class Format < ActiveRecord::Base
  has_many :bottles
end

app/models/grape.rb
class Grape < ActiveRecord::Base

  belongs_to :color
  has_many :compositions
  
end

app/models/offering.rb
class Offering < ActiveRecord::Base
  belongs_to :producer
  belongs_to :color
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :user
  belongs_to :cellar
end

app/models/producer.rb
class Producer < ActiveRecord::Base

  has_many :offerings
  belongs_to :region

end

app/models/region.rb
class Region < ActiveRecord::Base
  belongs_to :country
  has_many :producers
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password
  attr_accessible :name, :email, :description, :phone, :password, :password_confirmation

  has_many :owners
  has_many :cellars, :through => :owners



  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true, :length => { :maximum => 50 }
  validates :email, :presence => true, :format => { :with => email_regex }, :uniqueness => { :case_sensitive => false }

  # automatically creates the virtual attribute 'password_confirmation'
  validates :password, :presence => true, :confirmation => true, :length => { :within => 6..40 }

  before_save :encrypt_password

  default_scope :order => 'users.name ASC'

  # return true if the user's password matches the submitted password
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  # GET /producers
  # GET /producers.xml
  def index
    @producers = Producer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @producers }
    end
  end

  # GET /producers/1
  # GET /producers/1.xml
  def show
    @producer = Producer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @producer }
    end
  end

  # GET /producers/new
  # GET /producers/new.xml
  def new
    @producer = Producer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @producer }
    end
  end

  # GET /producers/1/edit
  def edit
    @producer = Producer.find(params[:id])
  end

  # POST /producers
  # POST /producers.xml
  def create
    @producer = Producer.new(params[:producer])

    respond_to do |format|
      if @producer.save
        format.html { redirect_to(@producer, :notice => 'Producer was successfully created.') }
        format.xml  { render :xml => @producer, :status => :created, :location => @producer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @producer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /producers/1
  # PUT /producers/1.xml
  def update
    @producer = Producer.find(params[:id])

    respond_to do |format|
      if @producer.update_attributes(params[:producer])
        format.html { redirect_to(@producer, :notice => 'Producer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @producer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /producers/1
  # DELETE /producers/1.xml
  def destroy
    @producer = Producer.find(params[:id])
    @producer.destroy

    respond_to do |format|
      format.html { redirect_to(producers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/bottles_helper.rb
module BottlesHelper
end

app/helpers/cellars_helper.rb
module CellarsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/formats_helper.rb
module FormatsHelper
end

app/helpers/grapes_helper.rb
module GrapesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def authenticate
    deny_access unless signed_in?
  end

  def deny_access
    store_location
    redirect_to signin_path, :notice => 'Please sign in to access this page.'
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

    def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/producers/_form.html.erb
<%= form_for(@producer) do |f| %>
  <% if @producer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producer.errors.count, "error") %> prohibited this producer from being saved:</h2>

      <ul>
      <% @producer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :region_id %><br />
    <%= f.collection_select(:region_id, Region.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/producers/edit.html.erb
<h1>Editing producer</h1>

<%= render 'form' %>

<%= link_to 'Show', @producer %> |
<%= link_to 'Back', producers_path %>

app/views/producers/index.html.erb
<h1>Listing producers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Region</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @producers.each do |producer| %>
  <tr>
    <td><%= producer.name %></td>
    <td><%= producer.region.name %></td>
    <td><%= producer.description %></td>
    <td><%= link_to 'Show', producer %></td>
    <td><%= link_to 'Edit', edit_producer_path(producer) %></td>
    <td><%= link_to 'Destroy', producer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Producer', new_producer_path %>

app/views/producers/new.html.erb
<h1>New producer</h1>

<%= render 'form' %>

<%= link_to 'Back', producers_path %>

app/views/producers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @producer.name %>
</p>

<p>
  <b>Region:</b>
  <%= @producer.region_id %>
</p>

<p>
  <b>Description:</b>
  <%= @producer.description %>
</p>


<%= link_to 'Edit', edit_producer_path(@producer) %> |
<%= link_to 'Back', producers_path %>